=== mlauriola/boson/libs/component/compiler/resources/boson.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Boson Configuration Schema",
    "type": "object",
    "additionalProperties": false,
    "required": ["target"],
    "properties": {
        "name": {
            "type": "string",
            "minLength": 1,
            "description": "The name of on application"
        },
        "entrypoint": {
            "type": "string",
            "minLength": 1,
            "description": "An entrypoint php file"
        },
        "target": {
            "type": "array",
            "minLength": 1,
            "description": "List of compilation targets",
            "items": {
                "$ref": "#/$defs/compilation-target"
            }
        },
        "output": {
            "type": "string",
            "minLength": 1,
            "description": "Compiler output build directory"
        },
        "root": {
            "type": "string",
            "minLength": 1,
            "description": "Compiler root directory"
        },
        "arch": {
            "type": "array",
            "description": "List of expected CPU architectures to compile",
            "items": {
                "type": "string",
                "minLength": 1,
                "description": "The name of expected CPU architecture"
            }
        },
        "platform": {
            "type": "array",
            "description": "List of expected OS families to compile",
            "items": {
                "type": "string",
                "minLength": 1,
                "description": "The name of expected OS family"
            }
        },
        "mount": {
            "type": "array",
            "description": "List of mount directories",
            "items": {
                "type": "string",
                "minLength": 1,
                "description": "Relative directory name"
            }
        },
        "build": {
            "type": "object",
            "description": "Configuration of included files to build",
            "additionalProperties": false,
            "properties": {
                "files": {
                    "type": "array",
                    "description": "List of included files to build",
                    "items": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Relative pathname to the file"
                    }
                },
                "directories": {
                    "type": "array",
                    "description": "List of included directories to build",
                    "items": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Relative pathname to the directory"
                    }
                },
                "finder": {
                    "type": "array",
                    "description": "List of included finder rules to build",
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "description": "Finder inclusion configuration",
                        "required": ["directory"],
                        "properties": {
                            "directory": {
                                "$ref": "#/$defs/filter-reference"
                            },
                            "not-directory": {
                                "$ref": "#/$defs/filter-reference"
                            },
                            "name": {
                                "$ref": "#/$defs/filter-reference"
                            },
                            "not-name": {
                                "$ref": "#/$defs/filter-reference"
                            }
                        }
                    }
                }
            }
        },
        "extensions": {
            "type": "array",
            "description": "List of required compile target PHP extensions",
            "items": {
                "type": "string",
                "minLength": 1,
                "description": "Name of required compile target PHP extension"
            }
        },
        "ini": {
            "type": "object",
            "description": "List of common additional compile target php.ini config variables",
            "$ref": "#/$defs/ini-values"
        },
        "box-version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$",
            "description": "The `humbug/box` package version"
        }
    },
    "$defs": {
        "compilation-target": {
            "type": "object",
            "required": ["type"],
            "anyOf": [
                {"$ref": "#/$defs/builtin-compilation-target"},
                {"$ref": "#/$defs/phar-compilation-target"},
                {"$ref": "#/$defs/generic-compilation-target"}
            ],
            "properties": {
                "output": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The compilation output directory name"
                }
            }
        },
        "generic-compilation-target": {
            "type": "object",
            "patternProperties": {
                "^type$": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The compilation target type"
                }
            }
        },
        "phar-compilation-target": {
            "type": "object",
            "patternProperties": {
                "^type$": {
                    "type": "string",
                    "enum": ["phar"],
                    "description": "The compilation target type (expected: phar)"
                }
            }
        },
        "builtin-compilation-target": {
            "type": "object",
            "patternProperties": {
                "^type$": {
                    "type": "string",
                    "enum": [
                        "windows", "win32", "win64", "win",
                        "linux", "nix",
                        "macos", "darwin", "mac", "osx"
                    ],
                    "description": "The compilation target type (expected: windows|linux|macos)"
                }
            },
            "properties": {
                "arch": {
                    "type": "string",
                    "enum": [
                        "amd64", "x86_64", "x64",
                        "aarch64", "arm64", "arm64ilp32"
                    ],
                    "description": "The compilation target architecture"
                },
                "ini": {
                    "type": "object",
                    "description": "List of specific compile target php.ini config variables",
                    "$ref": "#/$defs/ini-values"
                },
                "sfx": {
                    "type": "string",
                    "minLength": 1,
                    "description": "User defined SFX pathname for this target"
                }
            }
        },
        "filter-reference": {
            "oneOf": [
                {
                    "type": "string",
                    "description": "The name of file or directory",
                    "minLength": 1
                },
                {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string",
                        "description": "List of filenames or directories",
                        "minLength": 1
                    }
                }
            ]
        },
        "ini-values": {
            "type": "object",
            "description": "List of compile target php.ini config variables",
            "additionalProperties": false,
            "patternProperties": {
                "^.+$": {
                    "$ref": "#/$defs/ini-value",
                    "description": "Additional compile target php.ini config value"
                }
            }
        },
        "ini-value": {
            "anyOf": [
                {"$ref": "#/$defs/ini-string-value"},
                {"$ref": "#/$defs/ini-number-value"},
                {"$ref": "#/$defs/ini-boolean-value"}
            ]
        },
        "ini-string-value": {
            "type": "string",
            "description": "Additional compile target php.ini string value"
        },
        "ini-number-value": {
            "type": "number",
            "description": "Additional compile target php.ini number (int or float) value"
        },
        "ini-boolean-value": {
            "type": "boolean",
            "description": "Additional compile target php.ini boolean value"
        }
    }
}

=== mlauriola/boson/libs/component/compiler/resources/boson.json
{
    "name": "app",
    "entrypoint": "index.php",
    "target": [
        {
            "type": "windows",
            "arch": "amd64"
        },
        {
            "type": "linux",
            "arch": "amd64"
        },
        {
            "type": "linux",
            "arch": "arm64"
        },
        {
            "type": "macos",
            "arch": "amd64"
        },
        {
            "type": "macos",
            "arch": "arm64"
        },
        {
            "type": "phar"
        }
    ],
    "output": ".\/build",
    "build": {
        "directories": [
            "public"
        ],
        "finder": [
            {
                "directory": "src",
                "name": "*.php"
            },
            {
                "directory": "vendor",
                "not-directory": "vendor\/boson-php\/compiler",
                "name": "*.php"
            }
        ]
    },
    "ini": {
        "memory_limit": "128M"
    }
}
